# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push
jobs:
  # This workflow contains a single job called "build"
  build-node:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:16
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - run: node --version
    - run: npm --version
    - run: npm install
    - run: node index.js
